"""empty message

Revision ID: 7295620a5f4e
Revises: e0e130468222
Create Date: 2023-04-24 18:41:13.602810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7295620a5f4e'
down_revision = 'e0e130468222'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('endereco', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('endereco', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
