"""empty message

Revision ID: ba8a0f901594
Revises: 7295620a5f4e
Create Date: 2023-04-25 16:41:09.152406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba8a0f901594'
down_revision = '7295620a5f4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidente', schema=None) as batch_op:
        batch_op.alter_column('data_hora_retorno',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidente', schema=None) as batch_op:
        batch_op.alter_column('data_hora_retorno',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
