"""empty message

Revision ID: e0e130468222
Revises: ddd444f94056
Create Date: 2023-04-24 16:17:30.630690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0e130468222'
down_revision = 'ddd444f94056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endereco', sa.String(length=120), nullable=False),
    sa.Column('data_hora_queda', sa.DateTime(), nullable=False),
    sa.Column('data_hora_retorno', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('resposta')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resposta',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome_do_sistema', sa.VARCHAR(length=80), nullable=False),
    sa.Column('endereco', sa.VARCHAR(length=120), nullable=False),
    sa.Column('status_code', sa.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('incidente')
    # ### end Alembic commands ###
